name: Deploy to s3
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build files
    runs-on: ubuntu-latest
    steps: 
    - name: Setup node
      uses: actions/setup-node@v1
      with: 
          node-version: '16.x'
    - uses: actions/checkout@master
    - name: Deploy to s3
      env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
      run: |
        aws s3 sync regulations "s3://prod-phila-gov-website-s3/departments/department-of-records/regulations/"
        aws s3 sync new_regulations "s3://prod-phila-gov-website-s3/departments/department-of-records/regulations/aaaaa/"
        aws s3 sync regulations1 "s3://prod-phila-gov-website-s3/departments/department-of-records/regulations/"
        aws s3 sync regulations2 "s3://prod-phila-gov-website-s3/departments/department-of-records/regulations/"
        aws s3 sync regulations3 "s3://prod-phila-gov-website-s3/departments/department-of-records/regulations/"
        aws s3 sync regulations4 "s3://prod-phila-gov-website-s3/departments/department-of-records/regulations/"
        aws s3 sync regulations_json "s3://prod-phila-gov-website-s3/departments/department-of-records/regulations_json/" --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CF_INVALIDATE_PROD }} --paths "/*"
